apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  ports:
  - port: {{ .Values.deployment.containerport }}
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}